### ISSUE TITLE
My Stats kinda broken

### ISSUE THREAD

**Issue by SSundstrom** [cthit/hubbIT#148] opened 2016-11-16 12:50 UTC
Javascript issues, caused by Turbolinks. // jeeppson

**Comment by jesperlindstrom** [comment] 2016-11-16 12:57
The graph is broken when you click on the menu links, but when you reload the page it works. Probably caused by turbolinks. Xiaoming mentioned similar turbolinks related issues on the "add device" page.

**Comment by lindskogen** [comment] 2016-11-16 21:43
Fixed by 48374f3c54df8f450c72bfe59bd9ff5e5fda9f48

**Closed by lindskogen** 2016-11-16 21:43 UTC
